# Generated by Django 3.0.4 on 2020-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('bus_name', models.CharField(max_length=50)),
                ('ac_rate', models.IntegerField(default=0)),
                ('non_rate', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('allowance', models.IntegerField(default=0)),
                ('night_allowance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('car_name', models.CharField(max_length=50)),
                ('ac_rate', models.CharField(max_length=50)),
                ('extra_person', models.CharField(max_length=50)),
                ('extra_hour', models.CharField(max_length=50)),
                ('nigth_allowance', models.CharField(max_length=50)),
            ],
        ),
    ]
