# Generated by Django 3.0.4 on 2020-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umesh', '0002_bus_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
