# Generated by Django 3.0.4 on 2020-03-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umesh', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=50)),
            ],
        ),
    ]
