# Generated by Django 3.0.4 on 2020-03-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umesh', '0005_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
