# Generated by Django 3.0.4 on 2020-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umesh', '0006_header_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestic',
            name='slug',
            field=models.SlugField(default='TEST'),
            preserve_default=False,
        ),
    ]
